package Vista;

import Controlador.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class vista extends javax.swing.JFrame {
    DefaultTableModel model;
    controladorConsulta1 ctConsulta1;
    controladorConsulta2 ctConsulta2;
    controladorConsulta3 ctConsulta3;
    
    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        setLocationRelativeTo(null);
        this.ctConsulta1 = new controladorConsulta1();
        this.ctConsulta2 = new controladorConsulta2();
        this.ctConsulta3 = new controladorConsulta3();
        txtInforme.setSelectedIndex(0);
        String [] titulos = {"", "", "", ""};
        model = new DefaultTableModel(null, titulos);
        tableInforme.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInforme = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtInforme = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        labelD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(51, 51, 51));
        panelMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMain.setForeground(new java.awt.Color(51, 51, 51));
        panelMain.setMaximumSize(new java.awt.Dimension(550, 345));
        panelMain.setMinimumSize(new java.awt.Dimension(550, 345));
        panelMain.setPreferredSize(new java.awt.Dimension(550, 345));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrar.setBackground(new java.awt.Color(255, 153, 0));
        btnMostrar.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        panelMain.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        tableInforme.setBackground(new java.awt.Color(51, 51, 51));
        tableInforme.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tableInforme.setForeground(new java.awt.Color(255, 255, 255));
        tableInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tableInforme);

        panelMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 530, 220));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione el informe:");
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtInforme.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        txtInforme.setForeground(new java.awt.Color(255, 255, 255));
        txtInforme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Informe 1", "Informe 2", "Informe 3" }));
        txtInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInformeActionPerformed(evt);
            }
        });
        panelMain.add(txtInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelMain.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        labelD.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        labelD.setForeground(new java.awt.Color(255, 255, 255));
        labelD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelD.setText("Descripción del informe");
        labelD.setToolTipText("");
        panelMain.add(labelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 460, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSULTA A BASE DE DATOS PROYECTOS CONSTRUCCIÓN");
        jLabel2.setToolTipText("");
        panelMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        btnAbout.setBackground(new java.awt.Color(255, 153, 0));
        btnAbout.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("?");
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        panelMain.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInformeActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        int opcion = txtInforme.getSelectedIndex();
        if (opcion == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione el informe a consultar.");
        }
        else if (opcion == 1) {
            String [] titulos = {"ID LÍDER", "NOMBRE", "APELLIDO", "CIUDAD"};
            model = new DefaultTableModel(null, titulos);
            tableInforme.setModel(model);
            labelD.setText("Líderes de proyecto ordenados alfabéticamente por ciudad.");
            ResultSet resultado = this.ctConsulta1.getResult();
            try {
                while (resultado.next()) {
                Object [] registro = {resultado.getString("ID"), resultado.getString("NOMBRE"), resultado.getString("APELLIDO"), resultado.getString("CIUDAD")};
                model.addRow(registro);
                }
            }
            catch (Exception e) {
                System.out.println(e);
            }
        }
        else if (opcion == 2) {
            String [] titulos = {"ID PROYECTO", "CONSTRUCTORA", "HABITACIONES", "CIUDAD"};
            model = new DefaultTableModel(null, titulos);
            tableInforme.setModel(model);
            labelD.setText("Casas Campestres en Barranquilla, Santa Marta y Cartagena.");
            ResultSet resultado = this.ctConsulta2.getResult();
            try {
                while (resultado.next()) {
                Object [] registro = {resultado.getString("ID"), resultado.getString("CONSTRUCTORA"), resultado.getString("HABITACIONES"), resultado.getString("CIUDAD")};
                model.addRow(registro);
                }
            }
            catch (Exception e) {
                System.out.println(e);
            }
        }
        else if (opcion == 3) {
            String [] titulos = {"ID COMPRA", "CONSTRUCTORA", "BANCO"};
            model = new DefaultTableModel(null, titulos);
            tableInforme.setModel(model);
            labelD.setText("Compras hechas en Homecenter para proyectos en Salento.");
            ResultSet resultado = this.ctConsulta3.getResult();
            try {
                while (resultado.next()) {
                Object [] registro = {resultado.getString("ID"), resultado.getString("CONSTRUCTORA"), resultado.getString("BANCO")};
                model.addRow(registro);
                }
            }
            catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        JOptionPane.showMessageDialog(this, "Reto 5. Ciclo 2. MisiónTic. Ruta 2. UTP. Santiago Balcero. 2022.");
    }//GEN-LAST:event_btnAboutActionPerformed

    private void limpiarCampos() {
        txtInforme.setSelectedIndex(0);
        String [] titulos = {"", "", "", ""};
        model = new DefaultTableModel(null, titulos);
        tableInforme.setModel(model);
        model.setRowCount(0);
        labelD.setText("Descripción del informe");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelD;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTable tableInforme;
    private javax.swing.JComboBox<String> txtInforme;
    // End of variables declaration//GEN-END:variables
}
